### ISSUE TITLE
Go Button not Working

### ISSUE THREAD

**Issue by MaeghanColbyCorrea** [ccci-code/summerproject#16]
I added the CSS styling and everything was working fine perfectly while test running the code. However, the Go button is no longer working. I am not quite sure why it's not because I didn't change any major components of the code, only adding some classes to the HTML in the HTML and JavaScript file and then styling those classes. If anybody knows what the issue is, can you please let me know?

**Comment by ccci-code** [comment]
I can see your changes at:  https://ccci-code.github.io/summerproject/

The button seems to work there.  If I change the number of meals and click Ok, it displays the correct number of meal boxes below.  Is it not working when you view the index.html file in your browser?

**Comment by MaeghanColbyCorrea** [comment]
I'm seeing it now. There was probably just an issue with the loading on my laptop
